server:
  port: 9001
  servlet:
    context-path: /test-sys
    
spring:  application:    name: test-sys
  dubbo:
    application:
      id: test-sys
      name: test-sys
    registry:
      address: zookeeper://127.0.0.1:2181
    #server: true
    #protocol:
      #name: dubbo
      #port: 20881
    
#eureka配置
#eureka: 
  #client: 
    #service-url: 
      #defaultZone: http://127.0.0.1:9000/eureka/
      